application_record_path = "/home/jorge/PycharmProjects/caixa_datathon_group3/data/application_record.csv"
application_record_clean_path = "/home/jorge/PycharmProjects/caixa_datathon_group3/data/application_record_clean.csv"
application_record_filtered_path = "/home/jorge/PycharmProjects/caixa_datathon_group3/data/application_record_filtered.csv"
credit_score_path = "/home/jorge/PycharmProjects/caixa_datathon_group3/data/credit_record.csv"
df_model_path = "/home/jorge/PycharmProjects/caixa_datathon_group3/data/df_model.csv"